djangotatil/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tatilturapp.urls')),
    path('',include('django.contrib.auth.urls')),
]

tatilturapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "tatilturapp"

urlpatterns = [
    path('',views.homepage,name='homepage'),
    path('case/',views.case,name='case'),
    path('favori/',views.favourites,name='favourites'),
    path('signup/',views.SignUpView.as_view(),name='signup'),
    path('çanakkale/',views.çanakkale,name='çanakkale'),
    path('case/çanakkale/',views.caseçanakkale,name='caseçanakkale'),
    path('bursa/',views.bursa,name='bursa'),
    path('case/bursa/',views.casebursa,name='casebursa'),
    path('izmir/',views.izmir,name='izmir'),
    path('case/izmir/',views.caseizmir,name='caseizmir'),
    path('antalya',views.antalya,name='antalya'),
    path('case/antalya/',views.caseantalya,name='caseantalya'),
    path('istanbul/',views.istanbul,name='istanbul'),
    path('case/istanbul/',views.caseistanbul,name='caseistanbul'),
    path('muğla/',views.muğla,name='muğla'),
    path('case/muğla/',views.casemuğla,name='casemuğla'),
    path('trabzon/',views.trabzon,name='trabzon'),
    path('case/trabzon/',views.casetrabzon,name='casetrabzon'),
    path('adana/',views.adana,name='adana'),
    path('case/adana/',views.caseadana,name='caseadana'),
]

tatilturapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class TatilTur(models.Model):
    username = models.ForeignKey(User,on_delete=models.CASCADE,null=True)

    def __str__(self):
        return f"Username: {self.username}"

tatilturapp/forms.py
from django import forms
from django.forms import ModelForm
from tatilturapp.models import TatilTur

class SignUpForm(forms.Form):
    username_input = forms.CharField(label="Kullanıcı Adı",max_length=50)

class SignUpModelForm(ModelForm):
    class Meta:
        model = TatilTur
        fields = ["username"]

tatilturapp/views.py
from django.shortcuts import render , redirect
from . import models
from django.urls import reverse , reverse_lazy
from tatilturapp.forms import SignUpForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView

# Create your views here.

def homepage(request):
    if request.method == "post":
        form = SignUpForm(request.post)
        if form.is_valid():
            username = form.cleaned_data["username_input"]
            models.TatilTur.objects.create(username=username)
            return redirect(reverse('tatilturapp:case'))
        else:
            print("error in form!")
            return render(request,'tatilturapp/homepage.html', context={"form":form})
    else:
        form = SignUpForm()
        return render(request,'tatilturapp/homepage.html', context={"form":form})

@login_required(login_url="/login")
def case(request):
    return render(request,'tatilturapp/case.html')

def favourites(request):
    return render(request,'tatilturapp/favourites.html')

@login_required(login_url="/login")
def çanakkale(request):
    return render(request,'tatilturapp/çanakkale.html')

@login_required(login_url="/login")
def caseçanakkale(request):
    return render(request,'tatilturapp/caseçanakkale.html')

@login_required(login_url="/login")
def bursa(request):
    return render(request,'tatilturapp/bursa.html')

@login_required(login_url="/login")
def casebursa(request):
    return render(request,'tatilturapp/casebursa.html')

@login_required(login_url="/login")
def izmir(request):
    return render(request,'tatilturapp/izmir.html')

@login_required(login_url="/login")
def caseizmir(request):
    return render(request,'tatilturapp/caseizmir.html')

@login_required(login_url="/login")
def antalya(request):
    return render(request,'tatilturapp/antalya.html')

@login_required(login_url="/login")
def caseantalya(request):
    return render(request,'tatilturapp/caseantalya.html')

@login_required(login_url="/login")
def istanbul(request):
    return render(request,'tatilturapp/istanbul.html')

@login_required(login_url="/login")
def caseistanbul(request):
    return render(request,'tatilturapp/caseistanbul.html')

@login_required(login_url="/login")
def muğla(request):
    return render(request,'tatilturapp/muğla.html')

@login_required(login_url="/login")
def casemuğla(request):
    return render(request,'tatilturapp/casemuğla.html')

@login_required(login_url="/login")
def trabzon(request):
    return render(request,'tatilturapp/trabzon.html')

@login_required(login_url="/login")
def casetrabzon(request):
    return render(request,'tatilturapp/casetrabzon.html')

@login_required(login_url="/login")
def adana(request):
    return render(request,'tatilturapp/adana.html')

@login_required(login_url="/login")
def caseadana(request):
    return render(request,'tatilturapp/caseadana.html')

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = "registration/signup.html"

tatilturapp/templates/tatilturapp/bursa.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<br><br><br>

<h1><strong>Bursa Turu Sayfası</strong></h1>

<br>

<div class="row">

    <div class="col">
    <div class="card" style="width: 50rem; height: 45rem; border-color: blue;">
        <img src="{% static 'tatilturapp/bursa1.jpeg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title"><strong>Tur Rotası Bilgisi</strong></h5>
          <ol>
          <p class="card-text">Turumuz Bursa Ulu Camii ile başlayacak , ardından Bursa Atatürk Evi Müzesi ile devam edecek ve en son Bursa Arkeoloji Müzesi ile son bulacaktır.</p>
          <p class="card-text">Tur , içinde toplamda 2 tur hocası olacak ve 30 kişilik ekipler halinde gerçekleşecektir.</p>
          </ol>
        </div>
    </div>
    </div>

    <div class="col">
    <div class="card" style="width: 50rem; height: 45rem; border-color: blue;">
        <img src="{% static 'tatilturapp/bursa2.jpeg' %}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title"><strong>Turdaki Dinlenme ve Yemek Yerleri</strong></h5>
            <ol>
            <p class="card-text">İlk gün üç , diğer gün de iki olmak üzere toplamda beş tane dinlenme yeri tur içinde mevcuttur.</p>
            <p class="card-text">Yemek yeri olarak ise tur içindeki dinlenme yerinde sağlanacak ve her bir mola 1 saat olacaktır.</p>
            </ol>
        </div>
        </div>
    </div>

</div>

<br>

<div class="row">

    <div class="col">
    <div class="card" style="width: 50rem; height: 45rem; border-color: blue;">
        <img src="{% static 'tatilturapp/bursa3.jpeg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title"><strong>Tur Hediyeleri</strong></h5>
          <ol>
            <p class="card-text">Tur bitiminde sizlere turdaki gidilen yerler hakkında bilgi kitapçığı , anahtarlık ve bileklik gibi bir sürü hediye sağlanacaktır.</p>
          </ol>
        </div>
      </div>
      </div>

      <div class="col">
            <div class="card" style="width: 35rem; border-color: blue;">
              <div class="card-body">
                <p class="card-text"><strong>Bu turu satın almak istermisiniz ?</strong></p>
                <ol>
                <p class="card-text"><strong><h3>Fiyat:1.500TL</h3></strong></p>
                </ol>
                <a href="{% url 'tatilturapp:casebursa' %}" class="btn btn-danger">Satın Al</a>
              </div>
            </div>
      </div>

</div>

<br>

{% endblock %}

tatilturapp/templates/tatilturapp/caseadana.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<br><br><br>

<h1><strong>Kasa</strong></h1>

<br>

<h4 class="mb-3">Ürün Bilgileri</h4>
<form class="needs-validation" novalidate>
    <div class="row g-3">
        <div class="col-sm-6">
            <label class="form-label"><strong>Adana Turu</strong></label>
            <br>
            <a href="{% url 'tatilturapp:adana' %}"><img src="{% static 'tatilturapp/adana4.jpeg' %}" style="width: 15rem;"></a>
            <br>
            <label class="form-label"><strong><h3>Fiyat:1.750TL</h3></strong></label>
        </div>
    </div>
</form>

<div class="col-md-7 col-lg-8">
    <h4 class="mb-3">Fatura Bilgileri</h4>
    <form class="needs-validation" novalidate>
      <div class="row g-3">
        <div class="col-sm-6">
          <label for="firstName" class="form-label">Ad</label>
          <input type="text" class="form-control" id="firstName" placeholder="" value="" required>
          <div class="invalid-feedback">
            Adınız girmeniz gereklidir.
          </div>
        </div>

        <div class="col-sm-6">
          <label for="lastName" class="form-label">Soyad</label>
          <input type="text" class="form-control" id="lastName" placeholder="" value="" required>
          <div class="invalid-feedback">
            Soyadınızı girmeniz gereklidir.
          </div>
        </div>

        <div class="col-12">
          <label for="address" class="form-label">Adres</label>
          <input type="text" class="form-control" id="address" placeholder="1234 Ana Caddesi" required>
          <div class="invalid-feedback">
            Lütfen adresinizi giriniz.
          </div>
        </div>

      <hr class="my-4">

      <h4 class="mb-3">Ödeme Bilgileri</h4>

      <div class="my-3">
        <div class="form-check">
          <input id="credit" name="paymentMethod" type="radio" class="form-check-input" checked required>
          <label class="form-check-label" for="credit">Kredi Kartı</label>
        </div>
        <div class="form-check">
          <input id="debit" name="paymentMethod" type="radio" class="form-check-input" required>
          <label class="form-check-label" for="debit">Banka Kartı</label>
        </div>
        <div class="form-check">
          <input id="paypal" name="paymentMethod" type="radio" class="form-check-input" required>
          <label class="form-check-label" for="paypal">PayPal</label>
        </div>
      </div>

      <div class="row gy-3">
        <div class="col-md-6">
          <label for="cc-name" class="form-label">Kartın Üzerindeki Ad</label>
          <input type="text" class="form-control" id="cc-name" placeholder="" required>
          <small class="text-body-secondary">Bütün adı girmeniz gerekir.</small>
          <div class="invalid-feedback">
            Kartın Üzerindeki Adı girmeniz gereklidir.
          </div>
        </div>

        <div class="col-md-6">
          <label for="cc-number" class="form-label">Kredi Kartı Numarası</label>
          <input type="text" class="form-control" id="cc-number" placeholder="" required>
          <div class="invalid-feedback">
            Kredi Kartı Numarasını girmeniz önemlidir.
          </div>
        </div>

        <div class="col-md-3">
          <label for="cc-expiration" class="form-label">Son Kullanma Tarihi</label>
          <input type="text" class="form-control" id="cc-expiration" placeholder="" required>
          <div class="invalid-feedback">
            Lütfen son kullanma tarihini giriniz.
          </div>
        </div>

        <div class="col-md-3">
          <label for="cc-cvv" class="form-label">CVV</label>
          <input type="text" class="form-control" id="cc-cvv" placeholder="" required>
          <div class="invalid-feedback">
            Lütfen güvenlik kodunu giriniz.
          </div>
        </div>
      </div>

      <hr class="my-4">

      <button class="w-100 btn btn-primary btn-lg" type="submit">Ödeme</button>
    </form>
  </div>
</div>
</div>

<script src="{% static 'tatilturapp/checkout.js' %}"></script></body>

{% endblock %}

tatilturapp/templates/tatilturapp/favourites.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<br><br><br>

<h1><strong>Favoriler</strong></h1>

<br>

<div id="carouselExampleCaptions4" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions4" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions4" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions4" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <a href="{% url 'tatilturapp:antalya' %}"><img src="{% static 'tatilturapp/antalya1.jpeg' %}" class="d-block w-100" alt="..." style="width: 40rem; height: 35rem;"></a>
      <div class="carousel-caption d-none d-md-block">
        <h5 style="background-color: turquoise;"><strong>Antalya</strong></h5>
        <p style="background-color: turquoise;">Kurşunlu Şelalesi ve Karaalioğlu Parkı da dahil birçok yeri program içinde mevcuttur.</p>
      </div>
    </div>
    <div class="carousel-item">
      <a href="{% url 'tatilturapp:antalya' %}"><img src="{% static 'tatilturapp/antalya2.jpeg' %}" class="d-block w-100" alt="..." style="width: 40rem; height: 35rem;"></a>
      <div class="carousel-caption d-none d-md-block">
        <h5 style="background-color: turquoise;"><strong>Antalya</strong></h5>
        <p style="background-color: turquoise;">Program 4 günlük bir süreyi kapsamaktadır.</p>
      </div>
    </div>
    <div class="carousel-item">
      <a href="{% url 'tatilturapp:antalya' %}"><img src="{% static 'tatilturapp/antalya3.jpeg' %}" class="d-block w-100" alt="..." style="width: 40rem; height: 35rem;"></a>
      <div class="carousel-caption d-none d-md-block">
        <h5 style="background-color: turquoise;"><strong>Antalya</strong></h5>
        <p style="background-color: turquoise;">Tur içinde toplam 150 kişi olacaktır.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions4" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions4" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<br>

<div id="carouselExampleCaptions3" class="carousel slide">
  <div class="carousel-indicators" id="izmir">
    <button type="button" data-bs-target="#carouselExampleCaptions3" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions3" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions3" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <a href="{% url 'tatilturapp:izmir' %}"><img src="{% static 'tatilturapp/izmir1.jpeg' %}" class="d-block w-100 " alt="..." style="width: 40rem; height: 35rem;"></a>
      <div class="carousel-caption d-none d-md-block">
        <h5 style="background-color: green;"><strong>İzmir</strong></h5>
        <p style="background-color: green;">Konak Meydanı ve Saat Kulesi de dahil birçok ter tur programı içinde mevcuttur.</p>
      </div>
    </div>
    <div class="carousel-item">
      <a href="{% url 'tatilturapp:izmir' %}"><img src="{% static 'tatilturapp/izmir2.jpeg' %}" class="d-block w-100 " alt="..." style="width: 40rem; height: 35rem;"></a>
      <div class="carousel-caption d-none d-md-block">
        <h5 style="background-color: green;"><strong>İzmir</strong></h5>
        <p style="background-color: green;">Program 3 günlük bir süreyi kapsamaktadır.</p>
      </div>
    </div>
    <div class="carousel-item">
      <a href="{% url 'tatilturapp:izmir' %}"><img src="{% static 'tatilturapp/izmir3.jpeg' %}" class="d-block w-100 " alt="..." style="width: 40rem; height: 35rem;"></a>
      <div class="carousel-caption d-none d-md-block">
        <h5 style="background-color: green;"><strong>İzmir</strong></h5>
        <p style="background-color: green;">Tur içinde toplam 120 kişi olacaktır.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions3" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions3" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<br>

<div id="carouselExampleCaptions5" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions5" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions5" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions5" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <a href="{% url 'tatilturapp:istanbul' %}"><img src="{% static 'tatilturapp/istanbul1.jpeg' %}" class="d-block w-100" alt="..." style="width: 40rem; height: 35rem;"></a>
      <div class="carousel-caption d-none d-md-block">
        <h5 style="background-color: yellowgreen;"><strong>İstanbul</strong></h5>
        <p style="background-color: yellowgreen;">Topkapı Sarayı , Yerebatan Sarnıcı ve Kız Kulesi de dahil birçok yeri program içinde mevcuttur.</p>
      </div>
    </div>
    <div class="carousel-item">
      <a href="{% url 'tatilturapp:istanbul' %}"><img src="{% static 'tatilturapp/istanbul2.jpeg' %}" class="d-block w-100" alt="..." style="width: 40rem; height: 35rem;"></a>
      <div class="carousel-caption d-none d-md-block">
        <h5 style="background-color: yellowgreen;"><strong>İstanbul</strong></h5>
        <p style="background-color: yellowgreen;">Program 4 günlük bir süreyi kapsamaktadır.</p>
      </div>
    </div>
    <div class="carousel-item">
      <a href="{% url 'tatilturapp:istanbul' %}"><img src="{% static 'tatilturapp/istanbul3.jpeg' %}" class="d-block w-100" alt="..." style="width: 40rem; height: 35rem;"></a>
      <div class="carousel-caption d-none d-md-block">
        <h5 style="background-color: yellowgreen;"><strong>İstanbul</strong></h5>
        <p style="background-color: yellowgreen;">Tur içinde toplam 180 kişi olacaktır.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions5" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions5" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<br>

<div id="carouselExampleCaptions6" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions6" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions6" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions6" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <a href="{% url 'tatilturapp:muğla' %}"><img src="{% static 'tatilturapp/muğla1.jpeg' %}" class="d-block w-100" alt="..." style="width: 40rem; height: 35rem;"></a>
      <div class="carousel-caption d-none d-md-block">
        <h5 style="background-color: purple;"><strong>Muğla</strong></h5>
        <p style="background-color: purple;">Bodrum , Marmaris ve Fethiye de dahil birçok yeri program içinde mevcuttur.</p>
      </div>
    </div>
    <div class="carousel-item">
      <a href="{% url 'tatilturapp:muğla' %}"><img src="{% static 'tatilturapp/muğla2.jpeg' %}" class="d-block w-100" alt="..." style="width: 40rem; height: 35rem;"></a>
      <div class="carousel-caption d-none d-md-block">
        <h5 style="background-color: purple;"><strong>Muğla</strong></h5>
        <p style="background-color: purple;">Program 3 günlük bir süreyi kapsamaktadır.</p>
      </div>
    </div>
    <div class="carousel-item">
      <a href="{% url 'tatilturapp:muğla' %}"><img src="{% static 'tatilturapp/muğla3.jpeg' %}" class="d-block w-100" alt="..." style="width: 40rem; height: 35rem;"></a>
      <div class="carousel-caption d-none d-md-block">
        <h5 style="background-color: purple;"><strong>Muğla</strong></h5>
        <p style="background-color: purple;">Tur içinde toplam 90 kişi olacaktır.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions6" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions6" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<br>

{% endblock %}

tatilturapp/templates/tatilturapp/izmir.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<br><br><br>

<h1><strong>İzmir Turu Sayfası</strong></h1>

<br>

<div class="row">

<div class="col">
<div class="card" style="width: 50rem; height: 50rem; border-color: green;">
    <img src="{% static 'tatilturapp/izmir1.jpeg' %}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title"><strong>Tur Rotası Bilgisi</strong></h5>
      <ol>
      <p class="card-text">Turumuz Konak Meydanı ile başlayacak , ardından Saat Kulesi ile devam edecek ve en son İzmir içindeki müzeler ile son bulacaktır. </p>
      <p class="card-text">Tur , içinde toplamda 4 tur hocası ve 30 kişilik ekipler halinde gerçekleşecektir.</p>
      </ol>
    </div>
  </div>
  </div>

<div class="col">
    <div class="card" style="width: 50rem; height: 45rem; border-color: green;">
        <img src="{% static 'tatilturapp/izmir2.jpeg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title"><strong>Turdaki Dinlenme ve Yemek Yerleri</strong></h5>
          <ol>
          <p class="card-text">İlk , ikinci ve üçüncü günde üç tane olmak üzere toplamda dokuz tane dinlenme yeri tur içinde olacaktır.</p>
          <p class="card-text">Yemek yeri olarak ise tur içindeki dinlenme yerinde sağlanacak ve her bir mola 90 dakika olacaktır.</p>
          </ol>
        </div>
      </div>
</div>
</div>

<br>

<div class="row">

    <div class="col">
        <div class="card" style="width: 50rem; height: 45rem; border-color: green;">
            <img src="{% static 'tatilturapp/izmir3.jpeg' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title"><strong>Tur Hediyeleri</strong></h5>
              <ol>
              <p class="card-text">Tur bitiminde sizlere turdaki gidilen yerler hakkında bilgi kitapçığı , anahtarlık ve bileklik gibi bir sürü hediye sağlanacaktır.</p>
              </ol>
            </div>
          </div>
    </div>

    <div class="col">
        <div class="card" style="width: 35rem; border-color: green;">
            <p class="card-text"><strong>Bu turu satın almak istermisiniz ?</strong></p>
            <ol>
            <p class="card-text"><strong><h3>Fiyat:2.500TL</h3></strong></p>
            </ol>
            <a href="{% url 'tatilturapp:caseizmir' %}" class="btn btn-danger">Satın Al</a>
        </div>
    </div>

</div>

<br>

{% endblock %}

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>Tatil Tur Application</title>
</head>
<body>
    
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'tatilturapp:homepage' %}">Tatil Tur</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'tatilturapp:homepage' %}">Ana Sayfa</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tatilturapp:favourites' %}">Favoriler</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Giriş</a>
              </li>
              <li class="nav-item">
              <form id="logout-form" method="post" action="{% url 'logout' %}?next=/">
                <input type="hidden" name="csrfmiddlewaretoken" value="1u3BVeEbUWCuj6piRTtzgfQVMQPkjhzFwTxxqbZran3DmGIRuHhKCNeXakhEJxXO">{% csrf_token %}
                <button class="nav-link">Çıkış</button>
              </li>
            </form>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'tatilturapp:signup' %}">Kayıt</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tatilturapp:case' %}">Kasa</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      
      {% block content %}

      {% endblock %}

</body>
</html>